ALTER TABLE campaign_usage ADD COLUMN IF NOT EXISTS order_id INTEGER;
ALTER TABLE campaign_usage ADD COLUMN IF NOT EXISTS importo DECIMAL(12,2);
ALTER TABLE campaign_usage ADD COLUMN IF NOT EXISTS revoked BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE campaign_usage ADD COLUMN IF NOT EXISTS revoked_at TIMESTAMPTZ;
ALTER TABLE campaign_usage ADD COLUMN IF NOT EXISTS revoked_by INTEGER;
ALTER TABLE ordini_clienti ADD COLUMN IF NOT EXISTS codice_coupon TEXT;
